# Abort any circular requests
if ($http_X_LanCache_Processed_By = $hostname) {
  return 508;
}
proxy_set_header X-LanCache-Processed-By $hostname;
add_header X-LanCache-Processed-By $hostname,$http_X_LanCache_Processed_By always;

# Settings for proxying requests to upstream

# Pass the entire request URI through to the upstream server
proxy_pass http://$host$request_uri;

# Don't modify Refresh: and Location: headers sent from upstreams
proxy_redirect off; 

# Send Host: header from client's request to upstreams
proxy_set_header Host $host;
